/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/UCPci0anfQS
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { CardHeader, CardContent, Card } from "@/components/ui/card"

export function Cardexample() {
  return (
    <div className="flex w-full items-center justify-center flex-col gap-4 md:flex-row">
      <div className="relative group overflow-hidden rounded-lg">
        <div className="absolute inset-0 z-10 bg-opacity-25 bg-gray-900 transition-opacity opacity-0 flex items-center justify-center p-6">
          <span className="text-3xl font-semibold translate-x-2 transition-transform group-hover:translate-x-0">
            Discover
          </span>
        </div>
        <Card className="w-full">
          <CardContent className="p-6 flex items-center justify-center flex-col">
            <img
              alt="Cover image"
              className="rounded-lg object-cover"
              height="150"
              src="/placeholder.svg"
              style={{
                aspectRatio: "200/150",
                objectFit: "cover",
              }}
              width="200"
            />
            <CardHeader className="flex-1 items-center flex-col">
              <h4 className="text-lg font-semibold leading-none">Acoustic Sessions</h4>
              <p className="text-sm leading-none text-gray-500">Various Artists</p>
            </CardHeader>
          </CardContent>
        </Card>
      </div>
      <div className="relative group overflow-hidden rounded-lg">
        <div className="absolute inset-0 z-10 bg-opacity-25 bg-gray-900 transition-opacity opacity-0 flex items-center justify-center p-6">
          <span className="text-3xl font-semibold translate-x-2 transition-transform group-hover:translate-x-0">
            Explore
          </span>
        </div>
        <Card className="w-full">
          <CardContent className="p-6 flex items-center justify-center flex-col">
            <img
              alt="Cover image"
              className="rounded-lg object-cover"
              height="150"
              src="/placeholder.svg"
              style={{
                aspectRatio: "200/150",
                objectFit: "cover",
              }}
              width="200"
            />
            <CardHeader className="flex-1 items-center flex-col">
              <h4 className="text-lg font-semibold leading-none">Summer Vibes</h4>
              <p className="text-sm leading-none text-gray-500">Chill Mix</p>
            </CardHeader>
          </CardContent>
        </Card>
      </div>
      <div className="relative group overflow-hidden rounded-lg">
        <div className="absolute inset-0 z-10 bg-opacity-25 bg-gray-900 transition-opacity opacity-0 flex items-center justify-center p-6">
          <span className="text-3xl font-semibold translate-x-2 transition-transform group-hover:translate-x-0">
            Listen
          </span>
        </div>
        <Card className="w-full">
          <CardContent className="p-6 flex items-center justify-center flex-col">
            <img
              alt="Cover image"
              className="rounded-lg object-cover"
              height="150"
              src="/placeholder.svg"
              style={{
                aspectRatio: "200/150",
                objectFit: "cover",
              }}
              width="200"
            />
            <CardHeader className="flex-1 items-center flex-col">
              <h4 className="text-lg font-semibold leading-none">Morning Coffee</h4>
              <p className="text-sm leading-none text-gray-500">Wake Up!</p>
            </CardHeader>
          </CardContent>
        </Card>
      </div>
      <div className="relative group overflow-hidden rounded-lg">
        <div className="absolute inset-0 z-10 bg-opacity-25 bg-gray-900 transition-opacity opacity-0 flex items-center justify-center p-6">
          <span className="text-3xl font-semibold translate-x-2 transition-transform group-hover:translate-x-0">
            Enjoy
          </span>
        </div>
        <Card className="w-full">
          <CardContent className="p-6 flex items-center justify-center flex-col">
            <img
              alt="Cover image"
              className="rounded-lg object-cover"
              height="150"
              src="/placeholder.svg"
              style={{
                aspectRatio: "200/150",
                objectFit: "cover",
              }}
              width="200"
            />
            <CardHeader className="flex-1 items-center flex-col">
              <h4 className="text-lg font-semibold leading-none">Sunset Paradise</h4>
              <p className="text-sm leading-none text-gray-500">Island Beats</p>
            </CardHeader>
          </CardContent>
        </Card>
      </div>
      <div className="relative group overflow-hidden rounded-lg">
        <div className="absolute inset-0 z-10 bg-opacity-25 bg-gray-900 transition-opacity opacity-0 flex items-center justify-center p-6">
          <span className="text-3xl font-semibold translate-x-2 transition-transform group-hover:translate-x-0">
            Discover
          </span>
        </div>
        <Card className="w-full">
          <CardContent className="p-6 flex items-center justify-center flex-col">
            <img
              alt="Cover image"
              className="rounded-lg object-cover"
              height="150"
              src="/placeholder.svg"
              style={{
                aspectRatio: "200/150",
                objectFit: "cover",
              }}
              width="200"
            />
            <CardHeader className="flex-1 items-center flex-col">
              <h4 className="text-lg font-semibold leading-none">Acoustic Sessions</h4>
              <p className="text-sm leading-none text-gray-500">Various Artists</p>
            </CardHeader>
          </CardContent>
        </Card>
      </div>
      <div className="relative group overflow-hidden rounded-lg">
        <div className="absolute inset-0 z-10 bg-opacity-25 bg-gray-900 transition-opacity opacity-0 flex items-center justify-center p-6">
          <span className="text-3xl font-semibold translate-x-2 transition-transform group-hover:translate-x-0">
            Explore
          </span>
        </div>
        <Card className="w-full">
          <CardContent className="p-6 flex items-center justify-center flex-col">
            <img
              alt="Cover image"
              className="rounded-lg object-cover"
              height="150"
              src="/placeholder.svg"
              style={{
                aspectRatio: "200/150",
                objectFit: "cover",
              }}
              width="200"
            />
            <CardHeader className="flex-1 items-center flex-col">
              <h4 className="text-lg font-semibold leading-none">Summer Vibes</h4>
              <p className="text-sm leading-none text-gray-500">Chill Mix</p>
            </CardHeader>
          </CardContent>
        </Card>
      </div>
      <div className="relative group overflow-hidden rounded-lg">
        <div className="absolute inset-0 z-10 bg-opacity-25 bg-gray-900 transition-opacity opacity-0 flex items-center justify-center p-6">
          <span className="text-3xl font-semibold translate-x-2 transition-transform group-hover:translate-x-0">
            Listen
          </span>
        </div>
        <Card className="w-full">
          <CardContent className="p-6 flex items-center justify-center flex-col">
            <img
              alt="Cover image"
              className="rounded-lg object-cover"
              height="150"
              src="/placeholder.svg"
              style={{
                aspectRatio: "200/150",
                objectFit: "cover",
              }}
              width="200"
            />
            <CardHeader className="flex-1 items-center flex-col">
              <h4 className="text-lg font-semibold leading-none">Morning Coffee</h4>
              <p className="text-sm leading-none text-gray-500">Wake Up!</p>
            </CardHeader>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}
