/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/8m1iENiHrWI
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
* */
import Link from 'next/link';

import { Button } from '@/components/ui/button';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';

export function NavBarFour() {
  return (
    <header
      key="1"
      className="fixed inset-x-0 top-0 z-50 flex items-center justify-between border-b border-gray-200 px-6 py-4 shadow-lg dark:border-gray-700 dark:bg-gray-950 dark:text-gray-100"
    >
      <div className="flex items-center space-x-4">
        <Link
          className="inline-flex items-center rounded-md border border-gray-200 border-slate-200 bg-white px-4 py-2 text-sm font-medium text-gray-900 shadow-sm transition-shadow hover:border-gray-300 hover:bg-gray-100 hover:shadow-md focus:outline-none focus:ring-2 focus:ring-gray-500 focus:ring-offset-2 dark:border-gray-600 dark:border-slate-800 dark:bg-gray-800 dark:text-gray-100 dark:hover:border-gray-500 dark:hover:bg-gray-700"
          href="#"
        >
          <HomeIcon className="mr-2 size-5" />
          Home
        </Link>

        <div className="hidden lg:block">
          <Link
            className="inline-flex items-center rounded-md border border-gray-200 border-slate-200 bg-white px-4 py-2 text-sm font-medium text-gray-900 shadow-sm transition-shadow hover:border-gray-300 hover:bg-gray-100 hover:shadow-md focus:outline-none focus:ring-2 focus:ring-gray-500 focus:ring-offset-2 dark:border-gray-600 dark:border-slate-800 dark:bg-gray-800 dark:text-gray-100 dark:hover:border-gray-500 dark:hover:bg-gray-700"
            href="#"
          >
            <InfoIcon className="mr-2 size-5" />
            About
          </Link>
          <Link
            className="inline-flex items-center rounded-md border border-gray-200 border-slate-200 bg-white px-4 py-2 text-sm font-medium text-gray-900 shadow-sm transition-shadow hover:border-gray-300 hover:bg-gray-100 hover:shadow-md focus:outline-none focus:ring-2 focus:ring-gray-500 focus:ring-offset-2 dark:border-gray-600 dark:border-slate-800 dark:bg-gray-800 dark:text-gray-100 dark:hover:border-gray-500 dark:hover:bg-gray-700"
            href="#"
          >
            <BookIcon className="mr-2 size-5" />
            Guestbook
          </Link>
          <Link
            className="inline-flex items-center rounded-md border border-gray-200 border-slate-200 bg-white px-4 py-2 text-sm font-medium text-gray-900 shadow-sm transition-shadow hover:border-gray-300 hover:bg-gray-100 hover:shadow-md focus:outline-none focus:ring-2 focus:ring-gray-500 focus:ring-offset-2 dark:border-gray-600 dark:border-slate-800 dark:bg-gray-800 dark:text-gray-100 dark:hover:border-gray-500 dark:hover:bg-gray-700"
            href="#"
          >
            <BriefcaseIcon className="mr-2 size-5" />
            Portfolio
          </Link>
          <Link
            className="inline-flex items-center rounded-md border border-slate-200 border-transparent bg-white px-4 py-2 text-sm font-medium text-gray-900 shadow-sm transition-shadow hover:border-gray-200 hover:bg-gray-100 hover:shadow-md focus:outline-none focus:ring-2 focus:ring-gray-500 focus:ring-offset-2 dark:border-slate-800 dark:bg-gray-800 dark:text-gray-100 dark:hover:border-gray-600 dark:hover:bg-gray-700"
            href="#"
          >
            <GithubIcon className="mr-2 size-5" />
            Github
          </Link>
          <Link
            className="inline-flex items-center rounded-md border border-slate-200 border-transparent bg-white px-4 py-2 text-sm font-medium text-gray-900 shadow-sm transition-shadow hover:border-gray-200 hover:bg-gray-100 hover:shadow-md focus:outline-none focus:ring-2 focus:ring-gray-500 focus:ring-offset-2 dark:border-slate-800 dark:bg-gray-800 dark:text-gray-100 dark:hover:border-gray-600 dark:hover:bg-gray-700"
            href="#"
          >
            <LogInIcon className="mr-2 size-5" />
            Signin
          </Link>
          <Link
            className="inline-flex items-center rounded-md border border-slate-200 border-transparent bg-white px-4 py-2 text-sm font-medium text-gray-900 shadow-sm transition-shadow hover:border-gray-200 hover:bg-gray-100 hover:shadow-md focus:outline-none focus:ring-2 focus:ring-gray-500 focus:ring-offset-2 dark:border-slate-800 dark:bg-gray-800 dark:text-gray-100 dark:hover:border-gray-600 dark:hover:bg-gray-700"
            href="#"
          >
            <LogInIcon className="mr-2 size-5" />
            Signup
          </Link>
        </div>
      </div>
      <div className="flex items-center gap-2">
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button className="flex items-center gap-2" variant="outline">
              <GlobeIcon className="size-5" />
              <span>En</span>
              <ChevronDownIcon className="size-5" />
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end">
            <DropdownMenuItem>
              <Link className="flex items-center gap-2" href="#">
                <GlobeIcon className="size-5" />
                <span>Fr</span>
              </Link>
            </DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
        <Button className="lg:hidden" variant="outline">
          <MenuIcon className="size-7" />
          <span className="sr-only">Toggle navigation menu</span>
        </Button>
      </div>
      <div className="fixed inset-0 z-50 bg-gray-950 bg-opacity-80 backdrop-blur-sm lg:hidden">
        <div className="absolute inset-x-0 top-0 z-50 bg-gray-950 p-6 dark:bg-gray-950">
          <div className="flex items-center justify-between">
            <Link
              className="inline-flex items-center rounded-md bg-white px-4 py-2 text-sm font-medium text-gray-900 shadow-sm transition-shadow hover:bg-gray-100 hover:shadow-md focus:outline-none focus:ring-2 focus:ring-gray-500 focus:ring-offset-2 dark:bg-gray-800 dark:text-gray-100 dark:hover:bg-gray-700"
              href="#"
            >
              <HomeIcon className="mr-2 size-5" />
              Home
            </Link>
            <Button className="lg:hidden" variant="outline">
              <PanelTopCloseIcon className="size-7" />
              <span className="sr-only">Close navigation menu</span>
            </Button>
          </div>
          <div className="mt-6 grid gap-4">
            <Link
              className="inline-flex items-center rounded-md border border-slate-200 border-transparent bg-white px-4 py-2 text-sm font-medium text-gray-900 shadow-sm transition-shadow hover:border-gray-200 hover:bg-gray-100 hover:shadow-md focus:outline-none focus:ring-2 focus:ring-gray-500 focus:ring-offset-2 dark:border-slate-800 dark:bg-gray-800 dark:text-gray-100 dark:hover:border-gray-600 dark:hover:bg-gray-700"
              href="#"
            >
              <InfoIcon className="mr-2 size-5" />
              About
            </Link>
            <Link
              className="inline-flex items-center rounded-md border border-slate-200 border-transparent bg-white px-4 py-2 text-sm font-medium text-gray-900 shadow-sm transition-shadow hover:border-gray-200 hover:bg-gray-100 hover:shadow-md focus:outline-none focus:ring-2 focus:ring-gray-500 focus:ring-offset-2 dark:border-slate-800 dark:bg-gray-800 dark:text-gray-100 dark:hover:border-gray-600 dark:hover:bg-gray-700"
              href="#"
            >
              <BookIcon className="mr-2 size-5" />
              Guestbook
            </Link>
            <Link
              className="inline-flex items-center rounded-md border border-slate-200 border-transparent bg-white px-4 py-2 text-sm font-medium text-gray-900 shadow-sm transition-shadow hover:border-gray-200 hover:bg-gray-100 hover:shadow-md focus:outline-none focus:ring-2 focus:ring-gray-500 focus:ring-offset-2 dark:border-slate-800 dark:bg-gray-800 dark:text-gray-100 dark:hover:border-gray-600 dark:hover:bg-gray-700"
              href="#"
            >
              <BriefcaseIcon className="mr-2 size-5" />
              Portfolio
            </Link>
            <Link
              className="inline-flex items-center rounded-md border border-slate-200 border-transparent bg-white px-4 py-2 text-sm font-medium text-gray-900 shadow-sm transition-shadow hover:border-gray-200 hover:bg-gray-100 hover:shadow-md focus:outline-none focus:ring-2 focus:ring-gray-500 focus:ring-offset-2 dark:border-slate-800 dark:bg-gray-800 dark:text-gray-100 dark:hover:border-gray-600 dark:hover:bg-gray-700"
              href="#"
            >
              <GithubIcon className="mr-2 size-5" />
              Github
            </Link>
            <Link
              className="inline-flex items-center rounded-md border border-slate-200 border-transparent bg-white px-4 py-2 text-sm font-medium text-gray-900 shadow-sm transition-shadow hover:border-gray-200 hover:bg-gray-100 hover:shadow-md focus:outline-none focus:ring-2 focus:ring-gray-500 focus:ring-offset-2 dark:border-slate-800 dark:bg-gray-800 dark:text-gray-100 dark:hover:border-gray-600 dark:hover:bg-gray-700"
              href="#"
            >
              <LogInIcon className="mr-2 size-5" />
              Signin
            </Link>
            <Link
              className="inline-flex items-center rounded-md border border-slate-200 border-transparent bg-white px-4 py-2 text-sm font-medium text-gray-900 shadow-sm transition-shadow hover:border-gray-200 hover:bg-gray-100 hover:shadow-md focus:outline-none focus:ring-2 focus:ring-gray-500 focus:ring-offset-2 dark:border-slate-800 dark:bg-gray-800 dark:text-gray-100 dark:hover:border-gray-600 dark:hover:bg-gray-700"
              href="#"
            >
              <LogInIcon className="mr-2 size-5" />
              Signup
            </Link>
          </div>
        </div>
      </div>
    </header>
  );
}

function BookIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H20v20H6.5a2.5 2.5 0 0 1 0-5H20" />
    </svg>
  );
}

function BriefcaseIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="14" x="2" y="7" rx="2" ry="2" />
      <path d="M16 21V5a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16" />
    </svg>
  );
}

function ChevronDownIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m6 9 6 6 6-6" />
    </svg>
  );
}

function GithubIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
      <path d="M9 18c-4.51 2-5-2-7-2" />
    </svg>
  );
}

function GlobeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <line x1="2" x2="22" y1="12" y2="12" />
      <path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z" />
    </svg>
  );
}

function HomeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
      <polyline points="9 22 9 12 15 12 15 22" />
    </svg>
  );
}

function InfoIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="M12 16v-4" />
      <path d="M12 8h.01" />
    </svg>
  );
}

function LogInIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 3h4a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-4" />
      <polyline points="10 17 15 12 10 7" />
      <line x1="15" x2="3" y1="12" y2="12" />
    </svg>
  );
}

function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  );
}

function PanelTopCloseIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="18" x="3" y="3" rx="2" ry="2" />
      <line x1="3" x2="21" y1="9" y2="9" />
      <path d="m9 16 3-3 3 3" />
    </svg>
  );
}
